---
- name: holiday challenge playbook
  hosts: all
  gather_facts: no
  become_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Set authorized key for client servers
      ansible.posix.authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    
    - name: system update and upgrade 
      shell: sudo apt-get update && sudo apt-get upgrade -y
    
    - name: install nginx
      shell: sudo apt-get install nginx -y

    - name: install php8.1-fpm
      shell: sudo apt-get install php8.1-fpm -y

    - name: change file permission of sshd_config file
      shell: sudo chmod -R 0775 /etc/ssh/sshd_config
    
    - name: change  permission for project folder
      shell: sudo chmod -R 0777 /var/www/html

    - name: create project php file
      copy:
       src: /home/ubuntu/ruby.php
       dest: /var/www/html/ruby.php
      become: yes

    - name: start nginx
      shell: sudo systemctl start nginx

    - name:  permission to write to sites-available dir
      shell: sudo chmod -R 0777 /etc/nginx/sites-available

    - name: setup sites-available conf
      copy:
       src: /home/ubuntu/sites-avail-conf
       dest: /etc/nginx/sites-available/sites-avail-conf
      become: yes
      
    - name: link sites-avail to sites-enabled dir
      shell: sudo ln -s /etc/nginx/sites-available/sites-avail-conf /etc/nginx/sites-enabled/sites-avail-conf

    - name: relocate default sites-available file
      shell: sudo mv /etc/nginx/sites-available/default /home/ubuntu/default_sites-avail-file

    - name: delete default sites-enabled file
      shell: sudo rm /etc/nginx/sites-enabled/default

    - name: restart nginx
      shell: sudo systemctl restart nginx

